#! /usr/bin/env bash

if [[ -z $1 ]]; then
    echo "nlds-up requires a microservice to run"
    echo "nlds-up <microservice>"
    echo "    nlds_q"
    echo "    catalog_q"
    echo "    index_q"
    echo "    monitor_q"
    echo "    transfer_put_q"
    echo "    transfer_get_q"
    echo "    logging_q"
    echo "    archive_put_q"
    echo "    archive_get_q"
    echo "    archive_next"
    echo "    nlds-api"
    exit 1
fi

if [[ -z $NLDS_VENV ]]; then
    echo "NLDS_VENV environment variable not set"
    exit 1
else
    source $NLDS_VENV/bin/activate
fi

if [ $1 = 'nlds_q' ]; then
    nlds_q
elif [ $1 = 'catalog_q' ]; then
    catalog_q
elif [ $1 = 'index_q' ]; then
    index_q
elif [ $1 = 'monitor_q' ]; then
    monitor_q
elif [ $1 = 'transfer_put_q' ]; then
    transfer_put_q
elif [ $1 = 'transfer_get_q' ]; then
    transfer_get_q
elif [ $1 = 'logging_q' ]; then
    logging_q
elif [ $1 = 'archive_put_q' ]; then
    archive_put_q
elif [ $1 = 'archive_get_q' ]; then
    archive_get_q
elif [ $1 = 'archive_next' ]; then
    send_archive_next
elif [ $1 = 'nlds-api' ]; then
    uvicorn nlds.main:nlds --reload --log-level=trace --port=8000
fi

deactivate
