@startuml message_flow_put2

collections index as "Indexers" #lightblue

participant wex as "Exchange"

queue qw as "NLDS Q" #lightgrey
note over qw
    topic = nlds.#
end note
collections work as "NLDS\nWorker" #lightgrey
/'
database iddb as "Transaction DB" #lightgrey
'/
queue qt as "Transfer Q" #gold
note over qt
    topic = *.tran.*
end note
collections tran as "Transfers" #gold

participant obj as "Object\nStore" #GhostWhite

activate index
index -> wex : key=nlds.index.complete
deactivate index
activate wex
wex -> qw : key=nlds.index.complete
deactivate wex
activate qw
qw -> work : key=nlds.index.complete
deactivate qw
activate work
/'
work -> iddb : SELECT target,user,group WHERE id
activate iddb
iddb -> work : (target,user,group,id)
deactivate iddb
'/
work -> wex  : key=nlds.tran.transfer
deactivate work
activate wex
wex -> qt : key=nlds.tran.transfer
deactivate wex
activate qt
qt -> tran : key=nlds.tran.transfer
deactivate qt

activate tran
loop #lightgrey for file in indexed_list 
    tran -> obj : move file to storage
end
tran -> wex : key=nlds.tran.complete
deactivate tran
@enduml