@startuml message_flow_put

actor user as "User"
participant client as "Client"
participant server as "API server"
participant wex as "Exchange"

queue qw as "NLDS Q" #lightgrey
note over qw
    topic = nlds.#
end note
collections work as "NLDS\nWorker" #lightgrey
database iddb as "Transaction DB" #lightgrey

queue qs as "Index Q" #lightblue
note over qs
    topic = *.index.*
end note
collections index as "Indexers" #lightblue

user -> client : PUT(filelist,target,\n\tuser,group)
activate client
client -> server : PUT(filelist,target,\n\tuser,group,id)
deactivate client
activate server
server -> wex : key=nlds.put\nmsg=(filelist,target,\n\tuser,group,id)
deactivate server
activate wex
wex -> qw : key=nlds.put\nmsg=(filelist,target,\n\tuser,group,id)
deactivate wex
activate qw
qw -> work : key=nlds.put\nmsg=(filelist,target,\n\tuser,group,id)
deactivate qw

activate work
work -> wex : key=nlds.index.start\nmsg=(filelist,id)
activate wex
work -> iddb : INSERT(id,target,\n\tuser,group)
deactivate work
wex -> qs : key=nlds.index.start\nmsg=(filelist,id)
deactivate wex
note right of qs
    * here will match the calling
    application.
    `nlds` in this case.
    `gws` for group workspace scanner.
end note
activate qs
qs -> index : key=nlds.index.start\nmsg=(filelist,id)
deactivate qs
activate index
loop #lightgrey for subfile in filelist[::1000]
    index -> wex : key=nlds.index.index\nmsg=(subfilelist,id)
    activate wex
end
deactivate index
wex -> qs : key=nlds.index.index\nmsg=(subfilelist,id)
deactivate wex
activate qs
qs -> index : key=nlds.index.index\nmsg=(subfilelist,id)
deactivate qs
activate index
loop #lightgrey for file in subfilelist 
    alt file is directory
        index -> wex : key=nlds.index.index\nmsg=(file,id)
        activate wex
    else else
        index -> index : add file to\nindexed_list
    end
end
index -> wex : key=nlds.index.complete\nmsg=(indexed_list,id)
deactivate index
/'
wex -> qs : key=nlds.index.index\nmsg=(filelist,id)
'/
deactivate wex
/'
activate qs
qs -> index : key=nlds.index.index\nmsg=(filelist,id)
deactivate qs
activate index
loop #lightgrey for file in filelist 
    index -> index : add file to\nindexed_list
end
index -> wex : key=nlds.index.complete\nmsg=(indexed_list,id)
deactivate index
'/
@enduml