@startuml queue_structure

left to right direction
agent api_server as "API server" 

together {
    agent wex as "Work\nExchange" 
    note bottom of wex: type=topic
    queue wq as "Work Q" #lightgrey
    component work as "Work" #lightgrey
}
wex --> wq : key=work.*
wq --> work : prefetch=1

together {
    agent pex as "Process\nExchange"
    note bottom of pex: type=topic
}
together {
    queue sq as "Scan Q" #lightblue
    queue tq as "Transfer Q" #gold
    queue cq as "Catalog Q" #springgreen
}

note as N
    These could be
    the same exchange
end note

wex . N
pex . N

pex --> sq : key=scan.*
pex --> tq : key=tran.*
pex --> cq : key=cat.*

work --> pex : key=scan.*
work --> pex : key=tran.*
work --> pex : key=cat.*

queue mq as "Monitor Q" #tomato
wex --> mq : key=mon.*

together {
    component scan1 as "Scanner 1" #lightblue
    component scan2 as "Scanner 2" #lightblue
}

component tran1 as "Transfer" #gold
component cat1 as "Catalog" #springgreen
together {
    component mon1 as "Monitor" #tomato
    person user as "User"
}

api_server --> wex

sq --> scan1 : prefetch=1
sq --> scan2 : prefetch=1
tq --> tran1 : prefetch=1
cq --> cat1 : prefetch=1
mq --> mon1 : prefetch=1

user -> mon1

scan1 --> wex : key=work.scancomplete

@enduml