@startuml queue_structure

left to right direction
agent api_server as "API server" 

together {
    queue wq as "NLDS Q" #lightgrey
    component work as "NLDS" #lightgrey
    database iddb as "TransactionDB" #lightgrey
}

together {
    agent pex as "Exchange"
    note top of pex: type=topic
}

pex --> wq : key=nlds.*
wq -> work : prefetch=1
work -> iddb : SQL

together {
    queue sq as "Scan Q" #lightblue
    queue tq as "Transfer Q" #gold
    queue cq as "Catalog Q" #springgreen
}

pex --> sq : key=nlds.scan.*
pex --> tq : key=nlds.tran.*
pex --> cq : key=nlds.cat.*

work --> pex : key=nlds.scan.*
work --> pex : key=nlds.tran.*
work --> pex : key=nlds.cat.*

queue mq as "Monitor Q" #tomato
pex --> mq : key=nlds.mon.*

together {
    component scan1 as "Scanner 1" #lightblue
    component scan2 as "Scanner 2" #lightblue
}

component tran1 as "Transfer" #gold
component cat1 as "Catalog" #springgreen
together {
    component mon1 as "Monitor" #tomato
    person user as "User"
}

api_server -> pex

sq --> scan1 : prefetch=1
sq --> scan2 : prefetch=1
tq --> tran1 : prefetch=1
cq --> cat1 : prefetch=1
mq --> mon1 : prefetch=1

mon1 <- user

scan1 --> pex : key=nlds.scan.complete

@enduml