@startuml

left to right direction
skinparam arrowcolor black
skinparam objectbordercolor black
skinparam objectcolor automatic
skinparam legendbackgroundcolor white
legend top right 
    NLDS 
    V1.0 Neil/Bryan 14/09/21
end legend

package client #azure {

object "Client" as client
client : library = Requests

object "HTTP API" as httpapi
httpapi : library = FastAPI

object "JASMIN Accounts Portal" as jasminap
jasminap : library = OAuth2

} 

package engine #peachpuff {

object "Work Queue" as workqueue
workqueue : program = RabbitMQ

object "Transfer Processor" as transproc
transproc : library = FTS3

object "Tape" as tape
tape : interface = CTA

object "Object Storage" as objstore
objstore : interface = s3

}

package tools #seashell {

object "Work Processor" as workproc
workproc : language = Python

object "File Scanner" as filescan
filescan : language = Python

}

package system  #mistyrose {
object "Cache Processor" as cacheproc
cacheproc : language = Python

object "Cache Policies" as cachepol
cachepol : library = Open Policy Agent

object "Database Processor" as dbproc
dbproc : language = Python

object "Database" as db
db : type = ElasticSearch
}


client --> httpapi
client <-- jasminap : Token
httpapi <--> jasminap : Authenticate
httpapi --> workqueue

cacheproc <-- cachepol
workqueue <--> workproc
workqueue <--> transproc
cacheproc --> workqueue
workqueue --> dbproc
workqueue <--> filescan

db <-- dbproc

transproc --> objstore
transproc --> tape

db --> cacheproc



@enduml
