@startuml catalog_db

object "**Holding**" as holding {
    id [INT](unique)
    label [STRING](unique with user)
    user [STRING]
    group [STRING]
}

object "**Transaction**" as transaction {
    id [INT](unique)
    transaction_id [UUID_64|STRING](unique)
    ingest_time [DATETIME]
}

object "**Tag**" as tag {
    id [INT](unique)
    key [STRING]
    value [STRING]
}

object "**Aggregation**" as aggregation {
    id [INT](unique)
    tarname [STRING]
    checksum [STRING]
    algorithm [STRING]
}

object "**File**" as file {
    id [INT](unique)
    original_path [STRING]
    path_type [STRING]
    link_path [STRING]
    size [INT]
    user [STRING]
    group [STRING]
    file_permissions [INT]
}

object "**Location**" as location {
    id [INT](unique)
    storage_type [OBJECT_STORAGE|TAPE]
    storage_scheme [STRING]
    storage_netloc [STRING]
    root [STRING]
    path [STRING]
    access_time [DATETIME]
}

object "**Checksum**" as checksum {
    id [INT](unique)
    checksum [STRING](unique with algorithm)
    algorithm [STRING]
}

location "many"  *-- "1" aggregation
'holding "1" *-- "many" aggregation
transaction "1" *-- "many" file
holding "1" *-- "many" transaction
holding "1" *-- "many" tag
file "1" *-- "many" location
file "1" *-- "many" checksum
@enduml
