@startuml message_flow_put3

collections transfer_puts as "Transfer Puts" #gold

participant wex as "Exchange"

queue qw as "NLDS Q" #lightgrey
note over qw
    topic = nlds-api.nlds.#
end note
collections work as "NLDS\nWorker" #lightgrey

queue qc as "Catalog Q" #springgreen
collections catalog as "Cataloguers" #springgreen
database catalog_db as "Catalog DB" #springgreen
note over qc
    topic = #.catalog-put.#
end note

activate transfer_puts
transfer_puts -> wex : key=nlds-api.transfer-put.complete
deactivate transfer_puts

activate wex
wex -> qw : key=nlds-api.transfer-put.complete
deactivate wex

activate qw
qw -> work : key=nlds-api.transfer-put.complete
deactivate qw

activate work
work -> wex : key=nlds-api.catalog-put.start
deactivate work

activate wex
wex -> qc : key=nlds-api.catalog-put.start
deactivate wex

activate qc
qc -> catalog : key=(#).catalog-put.start
deactivate qc
note right of qc
    (#) here will match the calling
    application.
    `nlds-api` in this case.
end note

activate catalog
loop #lightgrey for file in transferred_list 
    catalog -> catalog_db : INSERT(user, group, id, target, file)
end
catalog -> wex : key=(#).catalog.put_complete
deactivate catalog


@enduml