@startuml message_flow_put2

collections index as "Indexers" #lightblue

participant wex as "Exchange"

queue qw as "NLDS Q" #lightgrey
note over qw
    topic = nlds-api.nlds.#
end note
collections work as "NLDS\nWorker" #lightgrey
/'
database iddb as "Transaction DB" #lightgrey
'/
queue qt as "Transfer Put Q" #gold
note over qt
    topic = #.transfer-put.#
end note
collections transfer_puts as "Transfer Puts" #gold

participant obj as "Object\nStore" #GhostWhite

activate index
index -> wex : key=nlds-api.index.complete
deactivate index
activate wex
wex -> qw : key=nlds-api.index.complete
deactivate wex
activate qw
qw -> work : key=nlds-api.index.complete
deactivate qw
activate work
/'
work -> iddb : SELECT target,user,group WHERE id
activate iddb
iddb -> work : (target,user,group,id)
deactivate iddb
'/
work -> wex  : key=nlds-api.transfer-put.start
deactivate work
activate wex
wex -> qt : key=nlds-api.transfer-put.start
deactivate wex
activate qt
qt -> transfer_puts : key=(#).transfer-put.start
deactivate qt
note right of qt
    (#) here will match the calling
    application.
    `nlds-api` in this case.
    `gws-api` for group workspace scanner.
end note

activate transfer_puts
loop #lightgrey for file in indexed_list 
    transfer_puts -> obj : move file to storage
end
transfer_puts -> wex : key=(#).transfer-put.complete
deactivate transfer_puts
@enduml