@startuml message_flow_get2

collections catalog as "Cataloguers" #springgreen

participant wex as "Exchange"

queue qw as "NLDS Q" #lightgrey
note over qw
    topic = nlds-api.nlds.*
end note
collections work as "NLDS\nWorker" #lightgrey

queue qt as "Transfer Get Q" #gold
note over qt
    topic = *.transfer-get.*
end note
collections transfer_get as "Transfer Get" #gold

participant obj as "Object\nStore" #GhostWhite

activate catalog
catalog -> wex : key=nlds-api.catalog-get.complete
deactivate catalog

activate wex
wex -> qw : key=nlds-api.catalog-get.complete
deactivate wex

activate qw
qw -> work : key=nlds-api.catalog-get.complete
deactivate qw

activate work
work -> wex : key=nlds-api.transfer-get.start
deactivate work

activate wex
wex -> qt : key=nlds-api.transfer-get.start
deactivate wex

activate qt
qt -> transfer_get : key=(*).transfer-get.start
deactivate qt
activate transfer_get

note right of qt
    (*) here will match the calling
    application.
    `nlds-api` in this case.
end note

loop #lightgrey for file in filelist 
    transfer_get -> obj : copy file to target
end
transfer_get -> wex : key=(*).transfer-get.complete
deactivate transfer_get

@enduml
