@startuml monitor_db

object "**Transaction State**" as transaction_state {
    id [INT](unique)
    transaction_id [UUID_64|STRING](unique)
    ' label [STRING](unique with user)?
    user [STRING]
    group [STRING]
    furthest_state [ROUTING | SPLITTING | INDEXING | TRANSFERRING | CATALOGING | COMPLETE | FAILED]
    split_count [INT] (set at index step)
    indexing_count [INT]
    transferring_count [INT]
    cataloguing_count [INT]
    complete_count [INT]
    failed_count [INT]
}


' holding "1" *-- "many" transaction

@enduml
