# encoding: utf-8
"""
message_keys.py
"""
__author__ = "Neil Massey and Jack Leland"
__date__ = "08 Apr 2024"
__copyright__ = "Copyright 2024 United Kingdom Research and Innovation"
__license__ = "BSD - see LICENSE file in top-level package directory"
__contact__ = "neil.massey@stfc.ac.uk"

# Refactored message keys into their own file

# Message json sections
DETAILS = "details"
ID = "id"
TRANSACT_ID = "transaction_id"
TIMESTAMP = "timestamp"
USER = "user"
GROUP = "group"
GROUPALL = "groupall"
TARGET = "target"
ROUTE = "route"
ERROR = "error"
TENANCY = "tenancy"
ACCESS_KEY = "access_key"
SECRET_KEY = "secret_key"
API_ACTION = "api_action"
JOB_LABEL = "job_label"
DATA = "data"
FILELIST = "filelist"
RETRIEVAL_FILELIST = "retrieval_dict"
TRANSACTIONS = "transactions"
LOG_TARGET = "log_target"
LOG_MESSAGE = "log_message"
META = "meta"
NEW_META = "new_meta"
LABEL = "label"
TAG = "tag"
DEL_TAG = "del_tag"
PATH = "path"
HOLDING_ID = "holding_id"
HOLDING_LIST = "holdings"
STATE = "state"
SUB_ID = "sub_id"
FAILURE = "failure"
USER_QUERY = "user_query"
GROUP_QUERY = "group_query"
RECORD_LIST = "records"
WARNING = "warning"
TAPE_URL = "tape_url"
TAPE_POOL = "tape_pool"
AGGREGATION_ID = "aggregation_id"
CHECKSUM = "checksum"
TARFILE= "tarfile"
PREPARE_ID = "prepare_id"
STORAGE_LOCATIONS = "storage_locations"
STORAGE_COUNT = "storage_count"
TYPE = "type"
TYPE_STANDARD = "standard"
TYPE_LOG = "log"
OBJECT_STORAGE = "OBJECT_STORAGE"
TAPE = "TAPE"