name: documentation

on: 
  workflow_run:
    workflows: [tests]
    types: [completed]

jobs:
  build:
    # needs: [tests, coverage]
    runs-on: ubuntu-latest
    steps:
    # Checkout and build the docs with sphinx
    - uses: actions/checkout@v2
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with: 
        docs-folder: "docs/"
        # pre-build-command: "mkdir /tmp/sphinx-log"
    - name: "Download badge"
      uses: actions/download-artifact@v3
      with:
        name: "covbadge"
    - name: "Download coverage report"
      uses: actions/download-artifact@v3
      with:
        name: "html-report"
    - name: "Copy coverage data into html folder"
      run: |
        mv htmlcov/ docs/build/html/htmlcov
        mv coverage.svg docs/build/html/htmlcov/coverage.svg
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: html-docs
        path: docs/build/html/
    # Deploys to the gh-pages branch if the commit was made to main, the 
    # gh-pages then takes over serving the html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html